Merge in healthcheck and misc fixes from Dev images

diff --git a/root/etc/cont-init.d/30-install b/root/etc/cont-init.d/30-install
--- a/root/etc/cont-init.d/30-install
+++ b/root/etc/cont-init.d/30-install
@@ -5,7 +5,9 @@ if [[ ! -d /config/www/Dashboard/.git ]]; then
   echo '-----------------------'
   echo '| Installing Organizr |'
   echo '-----------------------'
-  git clone -b v2-master https://github.com/causefx/Organizr /config/www/Dashboard
+  mkdir -p /config/www/Dashboard
+  git clone --progress --verbose -b v2-master https://github.com/causefx/Organizr /config/www/Dashboard
+  cd /config/www/Dashboard || (echo 'Failed to load Organizr repository folder'; exit)
   git rev-parse HEAD > /config/www/Dashboard/Github.txt
 elif [[ -d /config/www/Dashboard/.git ]]; then
   echo '-----------------------'
@@ -19,6 +21,9 @@ elif [[ -d /config/www/Dashboard/.git ]]; then
   git pull
   git rev-parse HEAD > /config/www/Dashboard/Github.txt
 fi
+
+# Make sure the config.php file is using the correct branch
+sed -i "s/'branch' => '[^']*',/'branch' =\> 'v2-master',/" /config/www/Dashboard/api/config/config.php
 
 # Set Permissions
 chown -R abc:abc \
