Even better git foo

diff --git a/root/etc/cont-init.d/30-install b/root/etc/cont-init.d/30-install
--- a/root/etc/cont-init.d/30-install
+++ b/root/etc/cont-init.d/30-install
@@ -10,10 +10,12 @@ elif [[ -d /config/www/Dashboard/.git ]]; then
   echo '-----------------------'
   echo '|  Updating Organizr  |'
   echo '-----------------------'
-  cd /config/www/Dashboard || return
-  git reset --hard origin/v2-master && \
-  git checkout v2-master && \
-  git pull --rebase
+  cd /config/www/Dashboard || (echo 'Failed to load Organizr repository folder'; exit)
+  git fetch
+  git reset --hard origin/v2-master
+  git checkout v2-master
+  git reset --hard origin/v2-master
+  git pull
 fi
 
 # Make sure the config.php file is using the correct branch
