Testing

diff --git a/root/etc/cont-init.d/30-install b/root/etc/cont-init.d/30-install
--- a/root/etc/cont-init.d/30-install
+++ b/root/etc/cont-init.d/30-install
@@ -9,7 +9,10 @@ if [[ ! -d /config/www/Dashboard/.git ]]; then
   echo 'Performing git clone...'
   git clone --progress --verbose -b v2-develop https://github.com/causefx/Organizr /config/www/Dashboard
   echo 'Sending info to Github.txt...'
+  cd /config/www/Dashboard || (echo 'Failed to load Organizr repository folder'; exit)
   git rev-parse HEAD > /config/www/Dashboard/Github.txt
+  echo 'Checking contents of Organizr directory...'
+  ls -la
 elif [[ -d /config/www/Dashboard/.git ]]; then
   echo '-----------------------'
   echo '|  Updating Organizr  |'
