Merge in healthcheck and misc fixes from Dev images

diff --git a/root/etc/cont-init.d/30-install b/root/etc/cont-init.d/30-install
--- a/root/etc/cont-init.d/30-install
+++ b/root/etc/cont-init.d/30-install
@@ -5,7 +5,9 @@ if [[ ! -d /config/www/Dashboard/.git ]]; then
   echo '-----------------------'
   echo '| Installing Organizr |'
   echo '-----------------------'
-  git clone -b v2-develop https://github.com/causefx/Organizr /config/www/Dashboard
+  mkdir -p /config/www/Dashboard
+  git clone --progress --verbose -b v2-master https://github.com/causefx/Organizr /config/www/Dashboard
+  cd /config/www/Dashboard || (echo 'Failed to load Organizr repository folder'; exit)
   git rev-parse HEAD > /config/www/Dashboard/Github.txt
 elif [[ -d /config/www/Dashboard/.git ]]; then
   echo '-----------------------'
@@ -13,30 +15,15 @@ elif [[ -d /config/www/Dashboard/.git ]]; then
   echo '-----------------------'
   cd /config/www/Dashboard || (echo 'Failed to load Organizr repository folder'; exit)
   git fetch
-  git reset --hard origin/v2-develop
-  git checkout v2-develop
-  git reset --hard origin/v2-develop
+  git reset --hard origin/v2-master
+  git checkout v2-master
+  git reset --hard origin/v2-master
   git pull
   git rev-parse HEAD > /config/www/Dashboard/Github.txt
 fi
 
-# Copy over Nginx status config file if it doesn't exist
-if [ ! -f /config/nginx/healthcheck.conf ]; then
-  echo '----------------------------------'
-  echo '| Copying Nginx status conf file |'
-  echo '----------------------------------'
-  cp /defaults/healthcheck.conf /config/nginx/healthcheck.conf
-else
-  :
-fi
-
-# Check for the include for the healthcheck conf and,
-# if it does not exist, add it
-if [[ $(grep -c healthcheck /config/nginx/site-confs/default) -eq 0 ]]; then
-  sed -i $'s|root /config/www/Dashboard;|root /config/www/Dashboard;\\\n        include /config/nginx/healthcheck.conf;|g' /config/nginx/site-confs/default
-elif [[ $(grep -c healthcheck /config/nginx/site-confs/default) -ge 1 ]]; then
-  :
-fi
+# Make sure the config.php file is using the correct branch
+sed -i "s/'branch' => '[^']*',/'branch' =\> 'v2-master',/" /config/www/Dashboard/api/config/config.php
 
 # Set Permissions
 chown -R abc:abc \
